id = "latex"
name = "LaTeX"
version = "0.1.8-dev"
schema_version = 1
authors = [
    "Ruben Zukic <ruben@zukic.net>",
    "Oli Callaghan <me@olicallaghan.com>",
    "Luke Naylor <luke.naylr@gmail.com>",
    "Jan Solanti <jhs@psonet.com>",
]
description = "LaTeX language server and syntax highlighting for Zed. See wiki on GitHub for help."
repository = "https://github.com/rzukic/zed-latex"

[language_servers.texlab]
name = "TexLab (Latex Language Server)"
language = "LaTeX"

[grammars.bibtex]
repository = "https://github.com/latex-lsp/tree-sitter-bibtex"
commit = "ccfd77db0ed799b6c22c214fe9d2937f47bc8b34"

[grammars.latex]
repository = "https://github.com/latex-lsp/tree-sitter-latex"
commit = "a6c812704b3d3e1541b0853aa0d6d561301320e1"
