id = "latex"
name = "LaTeX"
version = "0.0.4"
schema_version = 1
authors = [
    "Ruben Zukic <ruben@zukic.net>",
    "Oli Callaghan <me@olicallaghan.com>",
    "Luke Naylor <luke.naylr@gmail.com>"
]
description = "LaTeX language server and syntax highlighting for Zed"
repository = "https://github.com/rzukic/zed-latex"

[language_servers.texlab]
name = "TexLab (Latex Language Server)"
language = "LaTeX"

[grammars.bibtex]
repository = "https://github.com/latex-lsp/tree-sitter-bibtex"
commit = "ccfd77db0ed799b6c22c214fe9d2937f47bc8b34"

[grammars.latex]
repository = "https://github.com/latex-lsp/tree-sitter-latex"
commit = "a834712c5e04029a451a262456bf6290b8ef6f37"
